name: Test Pipeline (intentional failure)

on:
  push:
    branches: [testing-bot]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: This will fail
        run: exit 1
